# Generated by Django 5.0.1 on 2024-02-09 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_mail', models.EmailField(max_length=254)),
                ('doctor_password', models.CharField(max_length=50)),
                ('doctor_phoneno', models.BigIntegerField()),
                ('doctor_specialization', models.CharField(max_length=100)),
                ('doctor_img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_DOB', models.DateField()),
                ('patient_mail', models.EmailField(max_length=254)),
                ('patient_phoneno', models.BigIntegerField()),
                ('patient_address', models.CharField(max_length=400)),
                ('patient_password', models.CharField(max_length=50)),
                ('patient_img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('appoint_start_time', models.TimeField()),
                ('appoint_end_time', models.TimeField()),
                ('token', models.PositiveIntegerField()),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_appointment_system.doctor')),
                ('history_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_appointment_system.history')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_appointment_system.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('schedule_date', models.DateField()),
                ('schedule_start_time', models.TimeField()),
                ('schedule_end_time', models.TimeField()),
                ('maxpatient', models.PositiveIntegerField()),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_appointment_system.doctor')),
            ],
        ),
    ]
