# Generated by Django 5.0.1 on 2024-02-12 13:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_appointment_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appoint_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
